Landing Page
akib-raihan-sazim/Fancy_To_Do pull request #15
Opened 2024-07-25 06:21 UTC by akib-raihan-sazim

**Description of changes**
- Landing Page is added with some animation.
- Redirecting to landing page from the main index.

**Associated ticket link**
https://trello.com/c/FpbIyxNG

**Screenshot / Screen Recording**

https://github.com/user-attachments/assets/7d48d846-2873-49c9-9a2b-553afeaaf677

2024-07-25 10:40 UTC, ishmam-iqbal-sazim commented on pages/index.tsx
> +import { useEffect } from 'react';
```suggestion
import { useEffect } from "react";
```
Please try to set up prettier to automatically format the quotes, such that we consistently have double quotes across the application.

2024-07-25 10:40 UTC, ishmam-iqbal-sazim commented on pages/index.tsx
> +import { useRouter } from 'next/router'; // or 'next/navigation' for App Router
Let's refrain from leaving comments in our code.

2024-07-25 10:41 UTC, ishmam-iqbal-sazim commented on pages/LandingPage/index.tsx
> +import LandingPageContainer from '@/modules/LandingPage/containers/LandingPageContainer'
```suggestion
import LandingPageContainer from "@/modules/LandingPage/containers/LandingPageContainer"
```

2024-07-25 10:41 UTC, ishmam-iqbal-sazim commented on pages/index.tsx
> +    router.push('/LandingPage');
```suggestion
    router.push("/LandingPage");
```

2024-07-25 11:15 UTC, ragib-hossain-sazim commented
Landing Page route should be `localhost:3000`, default route. Remove `LandingPage` from the url please.

2024-07-25 11:23 UTC, ragib-hossain-sazim commented on pages/LandingPage/index.tsx
Page file name should be `index.page.tsx`.
No `Page` extension requird for page folder name. `LandingPage` => `Landing`

2024-07-25 11:34 UTC, ragib-hossain-sazim commented on styles/globals.css
> +@keyframes fadeIn {
Styles for containers and components should be written in their respective styles file not in globals.css.

For e.g: for your case move your styles to LandingPageContainer folder and create a LandingPageContainer.styles.tsx file and move styles there.

2024-07-26 10:58 UTC, ishmam-iqbal-sazim approved these changes

2024-07-26 11:00 UTC, ishmam-iqbal-sazim commented
Please tebase off of main prior to merging.

2024-07-26 18:27 UTC, ragib-hossain-sazim commented on modules/LandingPage/containers/LandingPageContainer.tsx
> +const FeatureItem: React.FC<{ icon: React.ReactNode; text: string }> = ({
Is this a component? Please move it from here to a seperate component file, if this is something you foresee as a shared component then move it under shared folder otherwise respective folder for this page.

2024-07-26 18:28 UTC, ragib-hossain-sazim commented on modules/LandingPage/containers/LandingPageContainer.tsx
> +const LandingPageContainer: React.FC = () => {
[NITIPICK] LandingPageContainer => LandingContainer. page keyword is redundant here. Please remove from other usecases as well.

2024-07-26 18:29 UTC, ragib-hossain-sazim requested changes
Pending comments

2024-07-26 21:55 UTC, merged