Task Detail Page
akib-raihan-sazim/Fancy_To_Do pull request #17
Opened 2024-07-26 09:08 UTC by akib-raihan-sazim

**Description of changes**
- Added Task Detail Page where user can delete, edit and mark complete.
- Added a logout button on the homepage.

**Associated ticket link**
https://trello.com/c/GcPL1b5J

**Screenshot / Screen Recording**

https://github.com/user-attachments/assets/f464d2ea-7b32-4fa7-97e0-06ee9f094084

2024-07-26 11:01 UTC, ishmam-iqbal-sazim commented on modules/HomePage/components/TaskItem/TaskItem.tsx
> +import { getPriorityColor } from "@/utils/priorityUtils";
library and @ imports should be separate and at the top

2024-07-26 11:06 UTC, ishmam-iqbal-sazim approved these changes
Approved pending comment

2024-07-26 18:41 UTC, ragib-hossain-sazim requested changes
Logout functionality is not in the scope of this PR. Please create a separate ticket and PR to address this issue

2024-07-29 13:12 UTC, ragib-hossain-sazim approved these changes

2024-07-29 13:13 UTC, ragib-hossain-sazim requested changes
Why do we have have 14 commits? Also there seems to be some older commits in the PR.

2024-07-29 13:29 UTC, akib-raihan-sazim commented
> Why do we have have 14 commits? Also there seems to be some older commits in the PR.

This happened while I was rebasing with the main branch. The older commits of main branch got appended.

2024-07-29 13:49 UTC, ragib-hossain-sazim commented
@akib-raihan-sazim Please resolve the commit issue before merging it to main.

2024-07-30 19:43 UTC, ragib-hossain-sazim approved these changes

2024-08-01 09:46 UTC, merged